spring.application.name=auth-service
server.port=1006
app.message=Client App Message
spring.cloud.config.import-check.enabled=false
#spring.config.import=configserver:http://localhost:8888
my.greeting.message=test

openapi.url = http://localhost:1006
openapi.env = local

spring.config.messages.basename = i18n/enum
spring.messages.encoding=UTF-8


# default path: h2-console
# http://localhost:1006/h2-ui/
# JDBC URL: jdbc:h2:file:./testdbproduct

spring.h2.console.enabled=true
spring.h2.console.path=/h2-ui

spring.datasource.url=jdbc:h2:file:./testdbproduct
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto= update

modelmapper.validate-enabled=true
modelmapper.skip-null-enabled=true
