# spring:
#   application:
#     name: auth-service
# #  server:
# #    port: 1006

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: auth-service
      # application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

# Custom metrics for our application
custom:
  metrics:
    enabled: true