---
## Default Elasticsearch configuration
cluster.name: "docker-cluster"
network.host: 0.0.0.0

## X-Pack settings
xpack.license.self_generated.type: basic
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true

## Memory settings
bootstrap.memory_lock: true

## Disk settings
cluster.routing.allocation.disk.threshold_enabled: false

## Discovery settings
discovery.type: single-node