global:
  resolve_timeout: 5m
  # Email configuration with Gmail SMTP
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'YOUR_ID@gmail.com'
  smtp_auth_username: 'YOUR_ID@gmail.com'
  # Replace with your App Password from Google Account
  smtp_auth_password: '<App Password>'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'instance', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: warning
    receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'YOUR_ID@gmail.com'
    send_resolved: true
    html: '{{ template "email.default.html" . }}'
    headers:
      subject: '[ALERT] {{ .GroupLabels.alertname }}'
templates:
- '/etc/alertmanager/template/*.tmpl'