groups:
- name: http_errors
  rules:
  - alert: HTTP500Errors
    expr: sum(increase(http_server_requests_seconds_count{status="500", application="auth-service"}[5m])) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "HTTP 500 errors detected"
      description: "{{ $value }} HTTP 500 errors in the last 5 minutes on {{ $labels.instance }}"
      dashboard_url: "http://localhost:3000/d/spring-boot-dashboard/spring-boot-dashboard"
  
  - alert: HighErrorRate
    expr: sum(rate(http_server_requests_seconds_count{status=~"5..", application="auth-service"}[5m])) / sum(rate(http_server_requests_seconds_count{application="auth-service"}[5m])) > 0.05
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "High error rate detected"
      description: "Error rate is {{ $value | humanizePercentage }} for the last 5 minutes on {{ $labels.instance }}"
      dashboard_url: "http://localhost:3000/d/spring-boot-dashboard/spring-boot-dashboard"
      
  - alert: APISpecific500Errors
    expr: sum by(uri) (increase(http_server_requests_seconds_count{status="500", application="auth-service"}[5m])) > 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "API endpoint returning 500 errors"
      description: "{{ $labels.uri }} has {{ $value }} HTTP 500 errors in the last 5 minutes"
      dashboard_url: "http://localhost:3000/d/spring-boot-dashboard/spring-boot-dashboard"